name: curr_affairs
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.7
  
  #service locator
  get_it: ^8.0.3

  #database
  floor: ^1.5.0

  #dateFormat
  intl: ^0.20.2
 
  #make requests to api
  retrofit: ^4.6.0

  #hooks
  flutter_hooks: ^0.21.2

  #image loader
  cached_network_image: ^3.4.1

  dio: ^5.4.0


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.5.0
  build_runner: ^2.4.8


flutter:

 
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

